apiVersion: v1
kind: Secret
metadata:
  name: vehicles-db-secret
  namespace: vehicles
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://vehicles-rds.cbiwugmus6fw.us-east-2.rds.amazonaws.com:5432/vehicles_db"
  SPRING_DATASOURCE_USERNAME: "admin_user"
  SPRING_DATASOURCE_PASSWORD: "mysecret"
