apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
  namespace: sales
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
        - name: sales-api
          image: 122610488782.dkr.ecr.us-east-2.amazonaws.com/sales:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: sales-db-secret
            - secretRef:
                name: sales-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
