apiVersion: v1
kind: Secret
metadata:
  name: sales-config
  namespace: sales
type: Opaque
stringData:
  VEHICLES_BASE_URL: "http://k8s-vehicles-vehicles-688b97eeb5-1318101442.us-east-2.elb.amazonaws.com"
