apiVersion: v1
kind: Secret
metadata:
  name: sales-db-secret
  namespace: sales
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://sales-rds.cbiwugmus6fw.us-east-2.rds.amazonaws.com:5432/sales_db"
  SPRING_DATASOURCE_USERNAME: "admin_user"
  SPRING_DATASOURCE_PASSWORD: "mysecret"
